
name: learn-github-workflows
on:
  push
jobs:
  check-calculator-operations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: 3.9.6
      - run:
          python3 -m unittest test_calculator.py