
name: learn-github-workflows
on:
  push
jobs:
  check-calculator-operations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt

      - name: run tests
        run: |
          python -m unittest test_calculator.py -v
