name: mini-project1-workflow
on:
  pull_request:
    branches: [ "main" ]
    types: [opened, edited, synchronize]

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - run: |
          pip install -r mini-project1/app/requirements.txt


      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          path: "mini-project1/app"
          args: "--count --select=E9,F63,F7,F82 --show-source --statistics"

      - name: Bandit Security Scan
        uses: gaurav-nelson/bandit-action@v1
        with:
          path: "mini-project1/app"
          level: "medium"
          exit_zero: true


      - name: Running Tests With Coverage
        run: |
          pytest app/tests/ --cov=app --cov-report=xml --cov-report=term-missing


      - name: Check coverage threshold
        uses: themichaelhall/check-code-coverage@v2
        with:
          report: coverage.xml
          required-percentage: 80